version: '3'
services:
  device_db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dontworrybehappy
      POSTGRES_PORT: 5432
      POSTGRES_DB: device_ms
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      assignment1-network:
        ipv4_address: 172.16.0.54
  
  device-microservice:
      image: a1-device-backend
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8081:8081"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://device_db:5432/device_ms
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: dontworrybehappy
      depends_on:
        - device_db
      networks:
        assignment1-network:
          ipv4_address: 172.16.0.55

volumes:
  db-data:


networks:
  assignment1-network:
    external: true